version: '3'

services: 
  app:
    build: .
    container_name: app
    image: aleckzts/laravel-app
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 90s .docker-laravel/start-dockerize.sh
    volumes:
      - .:/var/www
    networks: 
      - app-network
    depends_on: 
      - db
      - redis

  nginx:
    build: .docker-laravel/nginx
    container_name: nginx
    entrypoint: dockerize -template /etc/nginx/original.nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g 'daemon off;'
    restart: always
    tty: true
    environment: 
      - PHPFPM_HOST=app
      - PHPFPM_PORT=9000
    ports: 
      - "8000:80"
    volumes:
      - .:/var/www
    networks: 
      - app-network
    depends_on: 
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes: 
      - ./.docker-laravel/dbdata:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge