# build do frm com dockerize
FROM php:7.3.6-fpm-alpine3.9

WORKDIR /var/www

RUN apk add --no-cache openssl bash mysql-client nodejs npm
RUN docker-php-ext-install pdo pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN rm -rf /var/www/html
COPY . /var/www
RUN composer install && \
        php artisan config:cache && \
        chown -R www-data.www-data storage

RUN ln -s public html

EXPOSE 9000

ENTRYPOINT [ "php-fpm" ]


